=== Kinza-Khan/AI-202409D1TTS/xml/external.dtd
<!ELEMENT aptech (staff*, students*)>
<!ELEMENT staff (id , name , email)>
<!ELEMENT students (id , name , course)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ATTLIST staff  department CDATA #REQUIRED>

=== Kinza-Khan/AI-202409D1TTS/xml/external.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aptech SYSTEM "external.dtd" [
<!ENTITY aptech "aptech shahrah-e-faisal">
]>
<aptech>
    <staff department="HR">
        <id></id>
        <name></name>
        <email>&aptech;</email>
    </staff>
    <staff department="HR">
        <id></id>
        <name></name>
        <email></email>
    </staff>
    <students>
        <id></id>
        <name></name>
        <course></course>
    </students>
</aptech>
